/// Basit yerelleştirme sistemi. L.current global dil bayrağıdır;
/// t(key, args) o an geçerli dilde metni döner. Değişken kısımlar {ad}.
/// Bir dilde anahtar eksikse İngilizceye düşer.
enum Lang { tr, en, es, pt, fr, de, ru, it, id }

class L {
  static Lang current = Lang.tr;
}

/// Dil secicide gosterilen yerel adlar.
const Map<Lang, String> kLangNames = {
  Lang.tr: 'Türkçe',
  Lang.en: 'English',
  Lang.es: 'Español',
  Lang.pt: 'Português',
  Lang.fr: 'Français',
  Lang.de: 'Deutsch',
  Lang.ru: 'Русский',
  Lang.it: 'Italiano',
  Lang.id: 'Indonesia',
};

const Map<Lang, String> kLangCodes = {
  Lang.tr: 'tr',
  Lang.en: 'en',
  Lang.es: 'es',
  Lang.pt: 'pt',
  Lang.fr: 'fr',
  Lang.de: 'de',
  Lang.ru: 'ru',
  Lang.it: 'it',
  Lang.id: 'id',
};

Lang langFromCode(String code) =>
    kLangCodes.entries.firstWhere((e) => e.value == code, orElse: () => kLangCodes.entries.first).key;

/// Yildiz gorunumu adi: id 'klasik' -> t('skinKlasik').
String skinName(String id) => t('skin${id[0].toUpperCase()}${id.substring(1)}');

/// Cekirdek temasi adi: id 'kor' -> t('coreKor').
String coreThemeName(String id) => t('core${id[0].toUpperCase()}${id.substring(1)}');

String t(String key, [Map<String, String>? args]) {
  final map = _strings[L.current] ?? _strings[Lang.en]!;
  var s = map[key] ?? _strings[Lang.en]![key] ?? key;
  if (args != null) {
    for (final e in args.entries) {
      s = s.replaceAll('{${e.key}}', e.value);
    }
  }
  return s;
}

const Map<Lang, Map<String, String>> _strings = {
  Lang.en: {
    'appName': 'CONSTELLA',
    'tagline': 'connect the stars',
    'tapHint': 'Tap',
    'nearMiss': 'NEAR MISS!',
    'close': 'CLOSE',
    'mainMenu': 'MAIN MENU',
    'comingSoon': 'Coming soon!',
    'adNotReady': 'Ad not ready yet',
    'adSpacePlaceholder': 'Ad space',
    'hudLevel': 'Level {n}',
    'hudStarsLeft': '{n} stars left',
    'howtoTitle': 'How to play?',
    'howto1': 'Tap the screen to launch a star',
    'howto2': 'Pin stars onto the spinning core',
    'howto3': "Don't touch another star!",
    'howto4': 'In color levels: pin onto the matching colored slice',
    'start': 'START',
    'play': 'PLAY',
    'playLevel': 'PLAY  ·  LEVEL {n}',
    'streakDays': '{n} day streak',
    'store': 'STORE',
    'menu': 'MENU',
    'dailyQuestLabel': 'DAILY QUEST',
    'dailyQuestDone': 'Daily quest complete',
    'questLevels': 'clear {n} levels',
    'questNearmiss': 'get {n} near misses',
    'bestLevel': 'Level {n}',
    'level': 'LEVEL {n}',
    'completed': 'COMPLETE',
    'dustEarned': '+{n} ✦ stardust',
    'dustTotal': 'Total: ✦ {n}',
    'nextLevel': 'NEXT LEVEL  →',
    'upNext': 'up next: Level {n}',
    'failed': 'FAILED',
    'retryLevelCaps': 'RETRY THE LEVEL',
    'continueWithAd': '▶  CONTINUE  (Watch Ad)',
    'continueWithDust': '✦  CONTINUE  (✦{cost})',
    'retryLevel': 'RETRY  ·  LEVEL {n}',
    'sound': 'SOUND',
    'music': 'Music',
    'effects': 'Effects',
    'on': 'ON',
    'off': 'OFF',
    'language': 'LANGUAGE',
    'skipLevelItem': 'Skip a Level',
    'skipLevelDesc': 'one-time level skip',
    'godMode': 'God Mode',
    'godModeDesc': 'no ads + jump to any level',
    'monthlyMembership': 'Monthly Membership',
    'monthlyDesc': 'play ad-free',
    'other': 'OTHER',
    'share': 'Share',
    'rate': 'Rate Us',
    'footer': 'Constella · 2026',
    'dustBalance': '✦ {n} stardust',
    'starsSection': 'STARS',
    'coresSection': 'CORES',
    'select': 'SELECT',
    'selected': 'SELECTED',
    'confirmPurchaseTitle': 'Buy {name}?',
    'confirmPurchaseBody': 'This will cost ✦ {price} stardust\n(balance: ✦ {balance})',
    'insufficientBalanceBody': 'Not enough balance — needed: ✦ {price}\n(balance: ✦ {balance})',
    'cancel': 'CANCEL',
    'buy': 'BUY',
    'toastContinue': 'Continued! Your stars are back ✦',
    'toastDailyReward': 'Daily reward: +{n} ✦',
    'toastStreak': 'Streak: {n} days! 🔥',
    'toastQuestDone': 'Daily quest done! +{n} ✦',
    'toastSkinBought': '{name} unlocked! ✦',
    'toastInsufficientDust': 'Not enough stardust (✦{price})',
    'skinKlasik': 'Classic',
    'skinElmas': 'Diamond',
    'skinZumrut': 'Emerald',
    'skinNova': 'Nova',
    'skinKuyruklu': 'Comet',
    'coreKlasik': 'Classic',
    'coreKor': 'Ember',
    'coreAmetist': 'Amethyst',
    'coreYesim': 'Jade',
    'coreBuz': 'Frost',
  },
  Lang.tr: {
    'appName': 'CONSTELLA',
    'tagline': 'yildizlari birbirine bagla',
    'tapHint': 'Dokun',
    'nearMiss': 'KIL PAYI!',
    'close': 'KAPAT',
    'mainMenu': 'ANA MENU',
    'comingSoon': 'Yakinda!',
    'adNotReady': 'Reklam su an hazir degil',
    'adSpacePlaceholder': 'Reklam alani',
    'hudLevel': 'Bolum {n}',
    'hudStarsLeft': '{n} yildiz kaldi',
    'howtoTitle': 'Nasil oynanir?',
    'howto1': 'Ekrana dokun, yildizi firlat',
    'howto2': 'Yildizlari donen cekirdege sapla',
    'howto3': 'Baska bir yildiza degme!',
    'howto4': 'Renkli bolumde: kendi rengindeki dilime sapla',
    'start': 'BASLA',
    'play': 'OYNA',
    'playLevel': 'OYNA  ·  BOLUM {n}',
    'streakDays': '{n} gun serisi',
    'store': 'MAGAZA',
    'menu': 'MENU',
    'dailyQuestLabel': 'GUNLUK GOREV',
    'dailyQuestDone': 'Gunluk gorev tamamlandi',
    'questLevels': '{n} bolum gec',
    'questNearmiss': '{n} kil payi yap',
    'bestLevel': 'Bolum {n}',
    'level': 'BOLUM {n}',
    'completed': 'TAMAMLANDI',
    'dustEarned': '+{n} ✦ yildiz tozu',
    'dustTotal': 'Toplam: ✦ {n}',
    'nextLevel': 'SONRAKI BOLUM  →',
    'upNext': 'siradaki: Bolum {n}',
    'failed': 'BASARISIZ',
    'retryLevelCaps': 'BOLUMU TEKRAR DENE',
    'continueWithAd': '▶  DEVAM ET  (Reklam Izle)',
    'continueWithDust': '✦  DEVAM ET  (✦{cost})',
    'retryLevel': 'TEKRAR DENE  ·  BOLUM {n}',
    'sound': 'SES',
    'music': 'Muzik',
    'effects': 'Efektler',
    'on': 'ACIK',
    'off': 'KAPALI',
    'language': 'DIL',
    'skipLevelItem': 'Bir Bolum Atla',
    'skipLevelDesc': 'bir defalik gecis hakki',
    'godMode': 'God Mode',
    'godModeDesc': 'reklamsiz + istedigin bolume atla',
    'monthlyMembership': 'Aylik Uyelik',
    'monthlyDesc': 'reklamsiz oyna',
    'other': 'DIGER',
    'share': 'Paylas',
    'rate': 'Puan Ver',
    'footer': 'Constella · 2026',
    'dustBalance': '✦ {n} yildiz tozu',
    'starsSection': 'YILDIZLAR',
    'coresSection': 'CEKIRDEKLER',
    'select': 'SEC',
    'selected': 'SECILDI',
    'confirmPurchaseTitle': '{name} satin alinsin mi?',
    'confirmPurchaseBody': '✦ {price} yildiz tozu harcanacak\n(bakiye: ✦ {balance})',
    'insufficientBalanceBody': 'Yetersiz bakiye — gerekli: ✦ {price}\n(bakiye: ✦ {balance})',
    'cancel': 'VAZGEC',
    'buy': 'SATIN AL',
    'toastContinue': 'Devam! Yildizlarin geri geldi ✦',
    'toastDailyReward': 'Gunluk odul: +{n} ✦',
    'toastStreak': 'Seri: {n} gun! 🔥',
    'toastQuestDone': 'Gunluk gorev tamam! +{n} ✦',
    'toastSkinBought': '{name} alindi! ✦',
    'toastInsufficientDust': 'Yetersiz yildiz tozu (✦{price})',
    'skinKlasik': 'Klasik',
    'skinElmas': 'Elmas',
    'skinZumrut': 'Zumrut',
    'skinNova': 'Nova',
    'skinKuyruklu': 'Kuyruklu Yildiz',
    'coreKlasik': 'Klasik',
    'coreKor': 'Kor',
    'coreAmetist': 'Ametist',
    'coreYesim': 'Yesim',
    'coreBuz': 'Buz',
  },
  Lang.es: {
    'tagline': 'conecta las estrellas',
    'tapHint': 'Toca',
    'nearMiss': '¡POR POCO!',
    'close': 'CERRAR',
    'mainMenu': 'MENÚ PRINCIPAL',
    'comingSoon': '¡Próximamente!',
    'adNotReady': 'El anuncio no está listo',
    'adSpacePlaceholder': 'Espacio publicitario',
    'hudLevel': 'Nivel {n}',
    'hudStarsLeft': 'quedan {n} estrellas',
    'howtoTitle': '¿Cómo jugar?',
    'howto1': 'Toca la pantalla para lanzar una estrella',
    'howto2': 'Clava estrellas en el núcleo giratorio',
    'howto3': '¡No toques otra estrella!',
    'howto4': 'En niveles de color: clava en la porción del mismo color',
    'start': 'EMPEZAR',
    'play': 'JUGAR',
    'playLevel': 'JUGAR  ·  NIVEL {n}',
    'streakDays': 'racha de {n} días',
    'store': 'TIENDA',
    'menu': 'MENÚ',
    'dailyQuestLabel': 'MISIÓN DIARIA',
    'dailyQuestDone': 'Misión diaria completada',
    'questLevels': 'supera {n} niveles',
    'questNearmiss': 'logra {n} por poco',
    'bestLevel': 'Nivel {n}',
    'level': 'NIVEL {n}',
    'completed': 'COMPLETADO',
    'dustEarned': '+{n} ✦ polvo estelar',
    'dustTotal': 'Total: ✦ {n}',
    'nextLevel': 'SIGUIENTE NIVEL  →',
    'upNext': 'siguiente: Nivel {n}',
    'failed': 'FALLASTE',
    'retryLevelCaps': 'REINTENTA EL NIVEL',
    'continueWithAd': '▶  CONTINUAR  (Ver anuncio)',
    'continueWithDust': '✦  CONTINUAR  (✦{cost})',
    'retryLevel': 'REINTENTAR  ·  NIVEL {n}',
    'sound': 'SONIDO',
    'music': 'Música',
    'effects': 'Efectos',
    'on': 'ON',
    'off': 'OFF',
    'language': 'IDIOMA',
    'skipLevelItem': 'Saltar un nivel',
    'skipLevelDesc': 'salto único de nivel',
    'godModeDesc': 'sin anuncios + salta a cualquier nivel',
    'monthlyMembership': 'Suscripción mensual',
    'monthlyDesc': 'juega sin anuncios',
    'other': 'OTROS',
    'share': 'Compartir',
    'rate': 'Puntúanos',
    'dustBalance': '✦ {n} polvo estelar',
    'starsSection': 'ESTRELLAS',
    'coresSection': 'NÚCLEOS',
    'select': 'ELEGIR',
    'selected': 'ELEGIDO',
    'confirmPurchaseTitle': '¿Comprar {name}?',
    'confirmPurchaseBody': 'Costará ✦ {price} polvo estelar\n(saldo: ✦ {balance})',
    'insufficientBalanceBody': 'Saldo insuficiente — necesitas: ✦ {price}\n(saldo: ✦ {balance})',
    'cancel': 'CANCELAR',
    'buy': 'COMPRAR',
    'toastContinue': '¡Continúa! Tus estrellas volvieron ✦',
    'toastDailyReward': 'Recompensa diaria: +{n} ✦',
    'toastStreak': '¡Racha: {n} días! 🔥',
    'toastQuestDone': '¡Misión diaria hecha! +{n} ✦',
    'toastSkinBought': '¡{name} desbloqueado! ✦',
    'toastInsufficientDust': 'Polvo estelar insuficiente (✦{price})',
    'skinKlasik': 'Clásico',
    'skinElmas': 'Diamante',
    'skinZumrut': 'Esmeralda',
    'skinKuyruklu': 'Cometa',
    'coreKlasik': 'Clásico',
    'coreKor': 'Brasa',
    'coreAmetist': 'Amatista',
    'coreYesim': 'Jade',
    'coreBuz': 'Escarcha',
  },
  Lang.pt: {
    'tagline': 'conecte as estrelas',
    'tapHint': 'Toque',
    'nearMiss': 'QUASE!',
    'close': 'FECHAR',
    'mainMenu': 'MENU PRINCIPAL',
    'comingSoon': 'Em breve!',
    'adNotReady': 'O anúncio não está pronto',
    'adSpacePlaceholder': 'Espaço de anúncio',
    'hudLevel': 'Nível {n}',
    'hudStarsLeft': '{n} estrelas restantes',
    'howtoTitle': 'Como jogar?',
    'howto1': 'Toque na tela para lançar uma estrela',
    'howto2': 'Fixe estrelas no núcleo giratório',
    'howto3': 'Não toque em outra estrela!',
    'howto4': 'Em níveis de cor: fixe na fatia da cor certa',
    'start': 'COMEÇAR',
    'play': 'JOGAR',
    'playLevel': 'JOGAR  ·  NÍVEL {n}',
    'streakDays': 'sequência de {n} dias',
    'store': 'LOJA',
    'menu': 'MENU',
    'dailyQuestLabel': 'MISSÃO DIÁRIA',
    'dailyQuestDone': 'Missão diária concluída',
    'questLevels': 'passe {n} níveis',
    'questNearmiss': 'consiga {n} quase-erros',
    'bestLevel': 'Nível {n}',
    'level': 'NÍVEL {n}',
    'completed': 'CONCLUÍDO',
    'dustEarned': '+{n} ✦ pó estelar',
    'dustTotal': 'Total: ✦ {n}',
    'nextLevel': 'PRÓXIMO NÍVEL  →',
    'upNext': 'a seguir: Nível {n}',
    'failed': 'FALHOU',
    'retryLevelCaps': 'TENTE O NÍVEL DE NOVO',
    'continueWithAd': '▶  CONTINUAR  (Ver anúncio)',
    'continueWithDust': '✦  CONTINUAR  (✦{cost})',
    'retryLevel': 'TENTAR DE NOVO  ·  NÍVEL {n}',
    'sound': 'SOM',
    'music': 'Música',
    'effects': 'Efeitos',
    'on': 'ON',
    'off': 'OFF',
    'language': 'IDIOMA',
    'skipLevelItem': 'Pular um nível',
    'skipLevelDesc': 'pulo único de nível',
    'godModeDesc': 'sem anúncios + pule para qualquer nível',
    'monthlyMembership': 'Assinatura mensal',
    'monthlyDesc': 'jogue sem anúncios',
    'other': 'OUTROS',
    'share': 'Compartilhar',
    'rate': 'Avalie-nos',
    'dustBalance': '✦ {n} pó estelar',
    'starsSection': 'ESTRELAS',
    'coresSection': 'NÚCLEOS',
    'select': 'ESCOLHER',
    'selected': 'ESCOLHIDO',
    'confirmPurchaseTitle': 'Comprar {name}?',
    'confirmPurchaseBody': 'Custará ✦ {price} pó estelar\n(saldo: ✦ {balance})',
    'insufficientBalanceBody': 'Saldo insuficiente — necessário: ✦ {price}\n(saldo: ✦ {balance})',
    'cancel': 'CANCELAR',
    'buy': 'COMPRAR',
    'toastContinue': 'Continuou! Suas estrelas voltaram ✦',
    'toastDailyReward': 'Recompensa diária: +{n} ✦',
    'toastStreak': 'Sequência: {n} dias! 🔥',
    'toastQuestDone': 'Missão diária feita! +{n} ✦',
    'toastSkinBought': '{name} desbloqueado! ✦',
    'toastInsufficientDust': 'Pó estelar insuficiente (✦{price})',
    'skinKlasik': 'Clássico',
    'skinElmas': 'Diamante',
    'skinZumrut': 'Esmeralda',
    'skinKuyruklu': 'Cometa',
    'coreKlasik': 'Clássico',
    'coreKor': 'Brasa',
    'coreAmetist': 'Ametista',
    'coreYesim': 'Jade',
    'coreBuz': 'Gelo',
  },
  Lang.fr: {
    'tagline': 'reliez les étoiles',
    'tapHint': 'Touchez',
    'nearMiss': 'JUSTE !',
    'close': 'FERMER',
    'mainMenu': 'MENU PRINCIPAL',
    'comingSoon': 'Bientôt !',
    'adNotReady': "Publicité pas encore prête",
    'adSpacePlaceholder': 'Espace publicitaire',
    'hudLevel': 'Niveau {n}',
    'hudStarsLeft': '{n} étoiles restantes',
    'howtoTitle': 'Comment jouer ?',
    'howto1': "Touchez l'écran pour lancer une étoile",
    'howto2': 'Plantez les étoiles sur le noyau tournant',
    'howto3': 'Ne touchez pas une autre étoile !',
    'howto4': 'Niveaux couleur : plantez sur la part de la bonne couleur',
    'start': 'JOUER',
    'play': 'JOUER',
    'playLevel': 'JOUER  ·  NIVEAU {n}',
    'streakDays': 'série de {n} jours',
    'store': 'BOUTIQUE',
    'menu': 'MENU',
    'dailyQuestLabel': 'QUÊTE DU JOUR',
    'dailyQuestDone': 'Quête du jour terminée',
    'questLevels': 'terminez {n} niveaux',
    'questNearmiss': 'réussissez {n} passes serrées',
    'bestLevel': 'Niveau {n}',
    'level': 'NIVEAU {n}',
    'completed': 'TERMINÉ',
    'dustEarned': "+{n} ✦ poussière d'étoile",
    'dustTotal': 'Total : ✦ {n}',
    'nextLevel': 'NIVEAU SUIVANT  →',
    'upNext': 'à suivre : Niveau {n}',
    'failed': 'ÉCHEC',
    'retryLevelCaps': 'RÉESSAYER LE NIVEAU',
    'continueWithAd': '▶  CONTINUER  (Voir pub)',
    'continueWithDust': '✦  CONTINUER  (✦{cost})',
    'retryLevel': 'RÉESSAYER  ·  NIVEAU {n}',
    'sound': 'SON',
    'music': 'Musique',
    'effects': 'Effets',
    'on': 'ON',
    'off': 'OFF',
    'language': 'LANGUE',
    'skipLevelItem': 'Passer un niveau',
    'skipLevelDesc': 'saut de niveau unique',
    'godModeDesc': 'sans pub + accès à tout niveau',
    'monthlyMembership': 'Abonnement mensuel',
    'monthlyDesc': 'jouez sans pub',
    'other': 'AUTRE',
    'share': 'Partager',
    'rate': 'Notez-nous',
    'dustBalance': "✦ {n} poussière d'étoile",
    'starsSection': 'ÉTOILES',
    'coresSection': 'NOYAUX',
    'select': 'CHOISIR',
    'selected': 'CHOISI',
    'confirmPurchaseTitle': 'Acheter {name} ?',
    'confirmPurchaseBody': 'Cela coûte ✦ {price} poussière\n(solde : ✦ {balance})',
    'insufficientBalanceBody': 'Solde insuffisant — requis : ✦ {price}\n(solde : ✦ {balance})',
    'cancel': 'ANNULER',
    'buy': 'ACHETER',
    'toastContinue': 'On continue ! Vos étoiles sont revenues ✦',
    'toastDailyReward': 'Récompense du jour : +{n} ✦',
    'toastStreak': 'Série : {n} jours ! 🔥',
    'toastQuestDone': 'Quête du jour réussie ! +{n} ✦',
    'toastSkinBought': '{name} débloqué ! ✦',
    'toastInsufficientDust': 'Pas assez de poussière (✦{price})',
    'skinKlasik': 'Classique',
    'skinElmas': 'Diamant',
    'skinZumrut': 'Émeraude',
    'skinKuyruklu': 'Comète',
    'coreKlasik': 'Classique',
    'coreKor': 'Braise',
    'coreAmetist': 'Améthyste',
    'coreYesim': 'Jade',
    'coreBuz': 'Givre',
  },
  Lang.de: {
    'tagline': 'verbinde die Sterne',
    'tapHint': 'Tippen',
    'nearMiss': 'KNAPP!',
    'close': 'SCHLIESSEN',
    'mainMenu': 'HAUPTMENÜ',
    'comingSoon': 'Demnächst!',
    'adNotReady': 'Anzeige noch nicht bereit',
    'adSpacePlaceholder': 'Werbefläche',
    'hudLevel': 'Level {n}',
    'hudStarsLeft': 'noch {n} Sterne',
    'howtoTitle': 'Wie spielt man?',
    'howto1': 'Tippe, um einen Stern zu schießen',
    'howto2': 'Hefte Sterne an den drehenden Kern',
    'howto3': 'Berühre keinen anderen Stern!',
    'howto4': 'In Farb-Levels: auf das passende Farbsegment heften',
    'start': 'START',
    'play': 'SPIELEN',
    'playLevel': 'SPIELEN  ·  LEVEL {n}',
    'streakDays': '{n}-Tage-Serie',
    'store': 'SHOP',
    'menu': 'MENÜ',
    'dailyQuestLabel': 'TAGESAUFGABE',
    'dailyQuestDone': 'Tagesaufgabe erfüllt',
    'questLevels': 'schaffe {n} Level',
    'questNearmiss': 'schaffe {n} Beinahe-Treffer',
    'bestLevel': 'Level {n}',
    'level': 'LEVEL {n}',
    'completed': 'GESCHAFFT',
    'dustEarned': '+{n} ✦ Sternenstaub',
    'dustTotal': 'Gesamt: ✦ {n}',
    'nextLevel': 'NÄCHSTES LEVEL  →',
    'upNext': 'als Nächstes: Level {n}',
    'failed': 'GESCHEITERT',
    'retryLevelCaps': 'LEVEL WIEDERHOLEN',
    'continueWithAd': '▶  WEITER  (Video ansehen)',
    'continueWithDust': '✦  WEITER  (✦{cost})',
    'retryLevel': 'NOCHMAL  ·  LEVEL {n}',
    'sound': 'TON',
    'music': 'Musik',
    'effects': 'Effekte',
    'on': 'AN',
    'off': 'AUS',
    'language': 'SPRACHE',
    'skipLevelItem': 'Level überspringen',
    'skipLevelDesc': 'einmaliges Überspringen',
    'godModeDesc': 'keine Werbung + zu jedem Level springen',
    'monthlyMembership': 'Monats-Abo',
    'monthlyDesc': 'werbefrei spielen',
    'other': 'SONSTIGES',
    'share': 'Teilen',
    'rate': 'Bewerten',
    'dustBalance': '✦ {n} Sternenstaub',
    'starsSection': 'STERNE',
    'coresSection': 'KERNE',
    'select': 'WÄHLEN',
    'selected': 'GEWÄHLT',
    'confirmPurchaseTitle': '{name} kaufen?',
    'confirmPurchaseBody': 'Kostet ✦ {price} Sternenstaub\n(Guthaben: ✦ {balance})',
    'insufficientBalanceBody': 'Nicht genug Guthaben — nötig: ✦ {price}\n(Guthaben: ✦ {balance})',
    'cancel': 'ABBRECHEN',
    'buy': 'KAUFEN',
    'toastContinue': 'Weiter! Deine Sterne sind zurück ✦',
    'toastDailyReward': 'Tagesbelohnung: +{n} ✦',
    'toastStreak': 'Serie: {n} Tage! 🔥',
    'toastQuestDone': 'Tagesaufgabe erledigt! +{n} ✦',
    'toastSkinBought': '{name} freigeschaltet! ✦',
    'toastInsufficientDust': 'Nicht genug Sternenstaub (✦{price})',
    'skinKlasik': 'Klassisch',
    'skinElmas': 'Diamant',
    'skinZumrut': 'Smaragd',
    'skinKuyruklu': 'Komet',
    'coreKlasik': 'Klassisch',
    'coreKor': 'Glut',
    'coreAmetist': 'Amethyst',
    'coreYesim': 'Jade',
    'coreBuz': 'Frost',
  },
  Lang.ru: {
    'tagline': 'соедини звёзды',
    'tapHint': 'Нажми',
    'nearMiss': 'ЧУТЬ-ЧУТЬ!',
    'close': 'ЗАКРЫТЬ',
    'mainMenu': 'ГЛАВНОЕ МЕНЮ',
    'comingSoon': 'Скоро!',
    'adNotReady': 'Реклама ещё не готова',
    'adSpacePlaceholder': 'Место для рекламы',
    'hudLevel': 'Уровень {n}',
    'hudStarsLeft': 'осталось звёзд: {n}',
    'howtoTitle': 'Как играть?',
    'howto1': 'Нажми на экран, чтобы запустить звезду',
    'howto2': 'Прикрепляй звёзды к вращающемуся ядру',
    'howto3': 'Не задень другую звезду!',
    'howto4': 'В цветных уровнях: попадай в сектор своего цвета',
    'start': 'НАЧАТЬ',
    'play': 'ИГРАТЬ',
    'playLevel': 'ИГРАТЬ  ·  УРОВЕНЬ {n}',
    'streakDays': 'серия {n} дн.',
    'store': 'МАГАЗИН',
    'menu': 'МЕНЮ',
    'dailyQuestLabel': 'ЗАДАНИЕ ДНЯ',
    'dailyQuestDone': 'Задание дня выполнено',
    'questLevels': 'пройди {n} уровней',
    'questNearmiss': 'сделай {n} впритык',
    'bestLevel': 'Уровень {n}',
    'level': 'УРОВЕНЬ {n}',
    'completed': 'ПРОЙДЕНО',
    'dustEarned': '+{n} ✦ звёздной пыли',
    'dustTotal': 'Всего: ✦ {n}',
    'nextLevel': 'СЛЕДУЮЩИЙ  →',
    'upNext': 'далее: Уровень {n}',
    'failed': 'ПРОВАЛ',
    'retryLevelCaps': 'ПОВТОРИТЬ УРОВЕНЬ',
    'continueWithAd': '▶  ПРОДОЛЖИТЬ  (Реклама)',
    'continueWithDust': '✦  ПРОДОЛЖИТЬ  (✦{cost})',
    'retryLevel': 'ЗАНОВО  ·  УРОВЕНЬ {n}',
    'sound': 'ЗВУК',
    'music': 'Музыка',
    'effects': 'Эффекты',
    'on': 'ВКЛ',
    'off': 'ВЫКЛ',
    'language': 'ЯЗЫК',
    'skipLevelItem': 'Пропустить уровень',
    'skipLevelDesc': 'разовый пропуск',
    'godModeDesc': 'без рекламы + переход на любой уровень',
    'monthlyMembership': 'Месячная подписка',
    'monthlyDesc': 'играй без рекламы',
    'other': 'ПРОЧЕЕ',
    'share': 'Поделиться',
    'rate': 'Оценить',
    'dustBalance': '✦ {n} звёздной пыли',
    'starsSection': 'ЗВЁЗДЫ',
    'coresSection': 'ЯДРА',
    'select': 'ВЫБРАТЬ',
    'selected': 'ВЫБРАНО',
    'confirmPurchaseTitle': 'Купить {name}?',
    'confirmPurchaseBody': 'Это стоит ✦ {price} звёздной пыли\n(баланс: ✦ {balance})',
    'insufficientBalanceBody': 'Недостаточно — нужно: ✦ {price}\n(баланс: ✦ {balance})',
    'cancel': 'ОТМЕНА',
    'buy': 'КУПИТЬ',
    'toastContinue': 'Продолжаем! Звёзды вернулись ✦',
    'toastDailyReward': 'Награда дня: +{n} ✦',
    'toastStreak': 'Серия: {n} дн.! 🔥',
    'toastQuestDone': 'Задание дня выполнено! +{n} ✦',
    'toastSkinBought': '{name} открыт! ✦',
    'toastInsufficientDust': 'Мало звёздной пыли (✦{price})',
    'skinKlasik': 'Классика',
    'skinElmas': 'Алмаз',
    'skinZumrut': 'Изумруд',
    'skinKuyruklu': 'Комета',
    'coreKlasik': 'Классика',
    'coreKor': 'Уголёк',
    'coreAmetist': 'Аметист',
    'coreYesim': 'Нефрит',
    'coreBuz': 'Иней',
  },
  Lang.it: {
    'tagline': 'collega le stelle',
    'tapHint': 'Tocca',
    'nearMiss': 'PER UN PELO!',
    'close': 'CHIUDI',
    'mainMenu': 'MENU PRINCIPALE',
    'comingSoon': 'Presto!',
    'adNotReady': 'Annuncio non pronto',
    'adSpacePlaceholder': 'Spazio pubblicitario',
    'hudLevel': 'Livello {n}',
    'hudStarsLeft': '{n} stelle rimaste',
    'howtoTitle': 'Come si gioca?',
    'howto1': 'Tocca lo schermo per lanciare una stella',
    'howto2': 'Fissa le stelle sul nucleo rotante',
    'howto3': "Non toccare un'altra stella!",
    'howto4': 'Nei livelli colore: fissa sullo spicchio dello stesso colore',
    'start': 'INIZIA',
    'play': 'GIOCA',
    'playLevel': 'GIOCA  ·  LIVELLO {n}',
    'streakDays': 'serie di {n} giorni',
    'store': 'NEGOZIO',
    'menu': 'MENU',
    'dailyQuestLabel': 'MISSIONE DEL GIORNO',
    'dailyQuestDone': 'Missione giornaliera completata',
    'questLevels': 'supera {n} livelli',
    'questNearmiss': 'ottieni {n} quasi-errori',
    'bestLevel': 'Livello {n}',
    'level': 'LIVELLO {n}',
    'completed': 'COMPLETATO',
    'dustEarned': '+{n} ✦ polvere di stelle',
    'dustTotal': 'Totale: ✦ {n}',
    'nextLevel': 'LIVELLO SUCCESSIVO  →',
    'upNext': 'prossimo: Livello {n}',
    'failed': 'FALLITO',
    'retryLevelCaps': 'RIPROVA IL LIVELLO',
    'continueWithAd': '▶  CONTINUA  (Guarda annuncio)',
    'continueWithDust': '✦  CONTINUA  (✦{cost})',
    'retryLevel': 'RIPROVA  ·  LIVELLO {n}',
    'sound': 'AUDIO',
    'music': 'Musica',
    'effects': 'Effetti',
    'on': 'ON',
    'off': 'OFF',
    'language': 'LINGUA',
    'skipLevelItem': 'Salta un livello',
    'skipLevelDesc': 'salto singolo',
    'godModeDesc': 'niente pubblicità + salta a qualsiasi livello',
    'monthlyMembership': 'Abbonamento mensile',
    'monthlyDesc': 'gioca senza pubblicità',
    'other': 'ALTRO',
    'share': 'Condividi',
    'rate': 'Valutaci',
    'dustBalance': '✦ {n} polvere di stelle',
    'starsSection': 'STELLE',
    'coresSection': 'NUCLEI',
    'select': 'SCEGLI',
    'selected': 'SCELTO',
    'confirmPurchaseTitle': 'Comprare {name}?',
    'confirmPurchaseBody': 'Costa ✦ {price} polvere di stelle\n(saldo: ✦ {balance})',
    'insufficientBalanceBody': 'Saldo insufficiente — serve: ✦ {price}\n(saldo: ✦ {balance})',
    'cancel': 'ANNULLA',
    'buy': 'COMPRA',
    'toastContinue': 'Continua! Le tue stelle sono tornate ✦',
    'toastDailyReward': 'Premio giornaliero: +{n} ✦',
    'toastStreak': 'Serie: {n} giorni! 🔥',
    'toastQuestDone': 'Missione giornaliera completata! +{n} ✦',
    'toastSkinBought': '{name} sbloccato! ✦',
    'toastInsufficientDust': 'Polvere insufficiente (✦{price})',
    'skinKlasik': 'Classico',
    'skinElmas': 'Diamante',
    'skinZumrut': 'Smeraldo',
    'skinKuyruklu': 'Cometa',
    'coreKlasik': 'Classico',
    'coreKor': 'Brace',
    'coreAmetist': 'Ametista',
    'coreYesim': 'Giada',
    'coreBuz': 'Gelo',
  },
  Lang.id: {
    'tagline': 'hubungkan bintang',
    'tapHint': 'Ketuk',
    'nearMiss': 'NYARIS!',
    'close': 'TUTUP',
    'mainMenu': 'MENU UTAMA',
    'comingSoon': 'Segera hadir!',
    'adNotReady': 'Iklan belum siap',
    'adSpacePlaceholder': 'Ruang iklan',
    'hudLevel': 'Level {n}',
    'hudStarsLeft': '{n} bintang lagi',
    'howtoTitle': 'Cara bermain?',
    'howto1': 'Ketuk layar untuk meluncurkan bintang',
    'howto2': 'Tancapkan bintang ke inti yang berputar',
    'howto3': 'Jangan sentuh bintang lain!',
    'howto4': 'Di level warna: tancapkan pada irisan warna yang cocok',
    'start': 'MULAI',
    'play': 'MAIN',
    'playLevel': 'MAIN  ·  LEVEL {n}',
    'streakDays': 'rentetan {n} hari',
    'store': 'TOKO',
    'menu': 'MENU',
    'dailyQuestLabel': 'MISI HARIAN',
    'dailyQuestDone': 'Misi harian selesai',
    'questLevels': 'selesaikan {n} level',
    'questNearmiss': 'raih {n} nyaris',
    'bestLevel': 'Level {n}',
    'level': 'LEVEL {n}',
    'completed': 'SELESAI',
    'dustEarned': '+{n} ✦ debu bintang',
    'dustTotal': 'Total: ✦ {n}',
    'nextLevel': 'LEVEL BERIKUTNYA  →',
    'upNext': 'selanjutnya: Level {n}',
    'failed': 'GAGAL',
    'retryLevelCaps': 'ULANGI LEVEL',
    'continueWithAd': '▶  LANJUTKAN  (Tonton iklan)',
    'continueWithDust': '✦  LANJUTKAN  (✦{cost})',
    'retryLevel': 'ULANGI  ·  LEVEL {n}',
    'sound': 'SUARA',
    'music': 'Musik',
    'effects': 'Efek',
    'on': 'ON',
    'off': 'OFF',
    'language': 'BAHASA',
    'skipLevelItem': 'Lewati level',
    'skipLevelDesc': 'lewati sekali',
    'godModeDesc': 'tanpa iklan + lompat ke level mana pun',
    'monthlyMembership': 'Langganan bulanan',
    'monthlyDesc': 'main tanpa iklan',
    'other': 'LAINNYA',
    'share': 'Bagikan',
    'rate': 'Beri nilai',
    'dustBalance': '✦ {n} debu bintang',
    'starsSection': 'BINTANG',
    'coresSection': 'INTI',
    'select': 'PILIH',
    'selected': 'DIPILIH',
    'confirmPurchaseTitle': 'Beli {name}?',
    'confirmPurchaseBody': 'Ini seharga ✦ {price} debu bintang\n(saldo: ✦ {balance})',
    'insufficientBalanceBody': 'Saldo kurang — perlu: ✦ {price}\n(saldo: ✦ {balance})',
    'cancel': 'BATAL',
    'buy': 'BELI',
    'toastContinue': 'Lanjut! Bintangmu kembali ✦',
    'toastDailyReward': 'Hadiah harian: +{n} ✦',
    'toastStreak': 'Rentetan: {n} hari! 🔥',
    'toastQuestDone': 'Misi harian selesai! +{n} ✦',
    'toastSkinBought': '{name} terbuka! ✦',
    'toastInsufficientDust': 'Debu bintang kurang (✦{price})',
    'skinKlasik': 'Klasik',
    'skinElmas': 'Berlian',
    'skinZumrut': 'Zamrud',
    'skinKuyruklu': 'Komet',
    'coreKlasik': 'Klasik',
    'coreKor': 'Bara',
    'coreAmetist': 'Kecubung',
    'coreYesim': 'Giok',
    'coreBuz': 'Es',
  },
};
